controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

news:
    path: /news
    controller: App\Controller\NewsController::index

sekretka:
    path: /sekretka
    controller: App\Controller\SecretController::index

multiki:
    path: /multiki
    controller: App\Controller\MultikiController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index

adminPage:
    path: /admin/posts
    controller: App\Controller\AdminController::viewPosts
    
createPost:
    path: /admin/createpost
    controller: App\Controller\AdminController::createPost

deletePost:
    path: /admin/deletepost
    controller: App\Controller\AdminController::deletePost

viewPost:
    path: /admin/viewpost
    controller: App\Controller\AdminController::viewPost

updatePost:
    path: /admin/updatepost
    controller: App\Controller\AdminController::updatePost

adminLogin:
    path: /admin/login
    controller: App\Controller\AdminController::login